BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[CapsImages] (
    [id] INT NOT NULL IDENTITY(1,1),
    [imageUrl] VARCHAR(500) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [CapsImages_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [CapsImages_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
